version: '3'
services:
  opstack-deployer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GOROOT=/usr/lib/go
      - PATH=$PATH:/root/.foundry/bin
    volumes:
      - ./deploy-scripts/setup.sh:/app/setup.sh
    command: /app/setup.sh